### PR TITLE
Adding license

### PR DESCRIPTION
**Pull request by Letme**
README was pimped a bit and turned away from reStructured text to more GitHub accepted Markdown.

### CODE REVIEW

**Comment by bavovanachte** [comment]
Could you move back to rst? Github might be more in favour of md than RST, but the PYPI info pages are completely intolerant of markdown formatting.

**Comment by bavovanachte** [comment]
And the parsing of rst by github seems to work fine, no? At least for basic stuff it seems to work on one of my personal projects: https://github.com/bavovanachte/sphinx-wavedrom

**Comment by Letme** [comment]
Done and fixed.

**Comment by bavovanachte** [comment]
Thanks

**Pull request merged**
