### PR TITLE
Modify DOXYGEN_WARNING_REGEX to support multiline warnings

### PR DESCRIPTION
**Pull request by lit-af**
Should fix: #135

### CODE REVIEW

**Comment by JasperCraeghs** [comment]
I don't see the option "Workflow(s) awaiting approval" to trigger the GitHub Actions. Do you know what's wrong, @Letme ?

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by JasperCraeghs** [comment]
```
'This1 should not be treated as warning\ntestfile.c:6: warning: group test: ignoring title "Some test functions" that does not match old title "Some freaky test functions"\nThis should not be treated as warning2\ntestfile.c:8: warning: group test: ignoring title "Some test functions" that does not match old title "Some freaky test functions"\n'
```

**Comment by lit-af** [comment]
I look into it. You might be onto something with the indents on the multiline warnings.

Can you please tell me how to run the tests locally?

**Comment by JasperCraeghs** [comment]
You can run the tests with [`tox`](https://tox.wiki/en/4.12.1/) in a virtual environment.

`tox -e py310` when you have Python 3.10

**Comment by Letme** [comment]
can you update with latest master just to see if the tests run now?

I think it would be good to move this forward a bit.

**Comment by lit-af** [comment]
Sure. I'll try to find some time next week

**Pull request closed without merging**
