### PR TITLE
Allow for multiple log-files to be provided and fix #33

### LINKED ISSUE #33: issue with python3 and unicode
In our project:

```
$ python3 src/mlx/warnings.py -j tests/junit_double_fail.xml
Traceback (most recent call last):
  File "src/mlx/warnings.py", line 313, in <module>
    main()
  File "src/mlx/warnings.py", line 306, in main
    warnings.check(loghandle.read())
  File "src/mlx/warnings.py", line 221, in check
    checker.check(content)
  File "src/mlx/warnings.py", line 162, in check
    result = JUnitXml.fromstring(content)
  File "/usr/local/lib/python3.5/dist-packages/junitparser/junitparser.py", line 141, in fromstring
    instance._elem = etree.fromstring(text)
  File "src/lxml/lxml.etree.pyx", line 3228, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79609)
  File "src/lxml/parser.pxi", line 1843, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:119069)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

Weird enough tox didn't find it

### PR DESCRIPTION
**Pull request by SteinHeselmans**

### CODE REVIEW

**Comment by SteinHeselmans** [comment]
also fix #33  here

**Comment by bavovanachte** [comment]
Made some adjustments in #34 , to make sure that wildcard expansion can also be used on windows machines.

**Comment by SteinHeselmans** [comment]
Merged #34 (thanks @bavovanachte ), added integration test for junit and wildcard expansion in d53a2a5

**Comment by SteinHeselmans** [comment]
ready for final review/merge

**Comment by bavovanachte** [comment]
Why is CI failing? Seems like something to do with coverage. Do we care?

**Comment by SteinHeselmans** [comment]
coverage went down a bit because the code in main is not unit tested. I added an integration test to tox.ini but it doesn't seem to count for coverage...

I don't think we should care, it would be an improvement however if that integration test counts for coverage?

**Pull request merged**
