### PR TITLE
Remove runtime setuptools_scm dependency

### PR DESCRIPTION
**Pull request by bavovanachte**

### CODE REVIEW

**Comment by bavovanachte** [comment]
@bollenn could you review as well? Not entirely sure if I'm doing this correctly.

**Comment by bavovanachte** [comment]
Not sure why all of a sudden python 3.3 cannot be supported anymore :confused:

**Comment by bollenn** [comment]
Fine for me... I created an extra pull request for the docs https://github.com/melexis/warnings-plugin/pull/71

**Comment by SteinHeselmans** [comment]
so for py3.3, i suppose we just drop support for that?

**Comment by Letme** [comment]
Agreed- lets drop python 3.3 support and move on.

**Comment by bavovanachte** [comment]
(hopefully) dropped 3.3 support in baae94b

**Comment by Letme** [comment]
Did we figure if this is going to clash with other packaged mlx scripts inside mlx repo?

**Comment by bavovanachte** [comment]
Good point. I could rename to warning_version.py?

**Comment by Letme** [comment]
i would make it `__warnings_version__.py` (to keep primary script name exact), but if I remember correctly the `__version__.py` is somehow standardized. `warnings_version.py` is a bit tricky if you ask me since it looks like script, not internal file.

**Comment by bavovanachte** [comment]
Agreed. See d4f282c and 9e43167

**Pull request merged**
