### PR TITLE
Refactored checker according to discussion in #21

### PR DESCRIPTION
**Pull request by bavovanachte**

### CODE REVIEW

**Comment by bavovanachte** [comment]
@Letme made a quick PR to illustrate my intentions in this discussion: https://github.com/melexis/warnings-plugin/pull/21#pullrequestreview-46249521

**Comment by SteinHeselmans** [comment]
The goal was to have a courtesy object of each checker as a static member of WarningsPlugin in order to perform the settings per checker (min/max/debug/..., some might not be implemented yet). Accessing the checkers through the  checkerList isn't that easy, as you probably need to string compare the names in the objects.
By passing an object to the activate() function however, a user (implementing a different main) is free to construct and configure its own checker object, so that's fine.

For now, i like this solution better then what we've come up with (sorry for confusing everybody) so :+1: 

note: there is a merge conflict

**Comment by bavovanachte** [comment]
Yes, I'll have to adapt all the unit tests :smile:

**Comment by Letme** [comment]
Implemented the suggestions in #21

**Pull request closed without merging**
